#!/usr/bin/env python3
"""Generate the cuRobo XRDF *skeleton* for the OpenArm bimanual robot.

This builds the version-independent parts of the XRDF directly from the MoveIt
config so they never drift from the SRDF/joint_limits:

  * cspace        - the 14 arm joints (+ default seed pose)
  * limits        - acceleration/jerk (seeded from joint_limits.yaml, tune later)
  * tool_frames   - both hands
  * self_collision.ignore  - translated 1:1 from SRDF <disable_collisions>

What it does NOT produce: the `geometry:` collision-sphere section. Sphere
centers/radii must be fit to the actual meshes with cuRobo's XRDF editor
(Isaac Sim, inside the dev container). The emitted file leaves a clearly
marked placeholder there; cuRobo will refuse to load until it is filled in.

Usage (from this directory):
    python3 gen_xrdf_skeleton.py
Re-run whenever openarm_bimanual.srdf changes to refresh the ignore map.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRDF = HERE.parent / "openarm_bimanual.srdf"
OUT = HERE / "openarm_bimanual.xrdf"

ARM_JOINTS = [f"openarm_{s}_joint{i}" for s in ("left", "right") for i in range(1, 8)]

# Collision links per side (link0-7 + hand + 2 fingers + wristcam bracket).
COLLISION_LINKS = []
for s in ("left", "right"):
    COLLISION_LINKS += [f"openarm_{s}_link{i}" for i in range(8)]
    COLLISION_LINKS += [
        f"openarm_{s}_hand",
        f"openarm_{s}_left_finger",
        f"openarm_{s}_right_finger",
        f"openarm_{s}_wristcam_bracket",
    ]


# Distal links (forearm/wrist/hand) can actually reach across the centerline and
# collide; proximal links (shoulder/upper arm) cannot, but their over-approximate
# collision spheres false-overlap at rest. So only KEEP CHECKED the cross-arm
# pairs where BOTH links are distal.
DISTAL = ("link4", "link5", "link6", "link7", "hand", "finger", "wristcam")


def _arm_side(link):
    """'left'/'right' for an openarm link (token after 'openarm_'), else ''."""
    parts = link.split("_")
    return parts[1] if len(parts) > 1 and parts[1] in ("left", "right") else ""


def _distal(link):
    return any(t in link for t in DISTAL)


def parse_ignore_pairs(srdf_text):
    """Return {link: sorted[ignored...]} for SRDF-disabled pairs where BOTH links
    are arm links, but DROP distal<->distal cross-arm (left<->right) pairs so they
    stay collision-checked.

    The SRDF Setup Assistant marks many left<->right pairs "never in collision"
    (random sampling rarely crosses the two arms), so copying disable_collisions
    1:1 tells cuMotion to IGNORE left-vs-right contacts -> it plans the arms
    straight through each other. A deliberate goal CAN bring the forearms/hands
    together, so DISTAL cross-arm pairs must stay CHECKED. Proximal cross-arm
    pairs are kept ignored (the arms can't reach each other there, and the
    over-approximate spheres would false-collide at the rest pose otherwise).
    """
    pairs = re.findall(
        r'disable_collisions\s+link1="([^"]+)"\s+link2="([^"]+)"', srdf_text
    )
    ignore = {}
    dropped = 0
    for a, b in pairs:
        if not (a.startswith("openarm") and b.startswith("openarm")):
            continue
        sa, sb = _arm_side(a), _arm_side(b)
        if sa and sb and sa != sb and _distal(a) and _distal(b):
            dropped += 1          # distal cross-arm: keep it collision-checked
            continue
        ignore.setdefault(a, set()).add(b)
    if dropped:
        print(f"  dropped {dropped} distal cross-arm ignore pairs (kept collision-checked)")
    return {k: sorted(v) for k, v in sorted(ignore.items())}


def main():
    srdf = SRDF.read_text()
    ignore = parse_ignore_pairs(srdf)

    lines = []
    lines.append("format: xrdf")
    lines.append("format_version: 1.0")
    lines.append("")
    lines.append("# Auto-generated by gen_xrdf_skeleton.py from openarm_bimanual.srdf +")
    lines.append("# joint_limits.yaml. Do not hand-edit the cspace/ignore blocks; regenerate.")
    lines.append("# The geometry: spheres block MUST be produced with cuRobo's XRDF editor.")
    lines.append("")
    lines.append("default_joint_positions:")
    for j in ARM_JOINTS:
        lines.append(f"  {j}: 0.0")
    lines.append("")
    lines.append("cspace:")
    lines.append("  joint_names:")
    for j in ARM_JOINTS:
        lines.append(f'    - "{j}"')
    # accel mirrors joint_limits.yaml (1.0 rad/s^2, conservative). Raise after
    # validating hardware behaviour at higher speeds, same as the MoveIt limits.
    lines.append("  acceleration_limits: [" + ", ".join(["1.0"] * len(ARM_JOINTS)) + "]")
    lines.append("  jerk_limits: [" + ", ".join(["100.0"] * len(ARM_JOINTS)) + "]")
    lines.append("")
    lines.append('tool_frames: ["openarm_left_hand", "openarm_right_hand"]')
    lines.append("")
    lines.append("collision:")
    lines.append('  geometry: "openarm_bimanual_collision_spheres"')
    lines.append("  buffer_distance:")
    for lk in COLLISION_LINKS:
        lines.append(f"    {lk}: 0.005")
    lines.append("")
    lines.append("self_collision:")
    lines.append('  geometry: "openarm_bimanual_collision_spheres"')
    lines.append("  buffer_distance:")
    for lk in COLLISION_LINKS:
        lines.append(f"    {lk}: 0.02")
    lines.append("  ignore:")
    for link, others in ignore.items():
        lines.append(f"    {link}:")
        for o in others:
            lines.append(f'      - "{o}"')
    lines.append("")
    lines.append("geometry:")
    lines.append("  openarm_bimanual_collision_spheres:")
    lines.append("    spheres:")
    lines.append("      # >>> PLACEHOLDER <<<")
    lines.append("      # Fill with sphere center/radius per link using cuRobo's XRDF editor")
    lines.append("      # (Isaac Sim, inside the dev container) fit to the OpenArm meshes.")
    lines.append("      # cuRobo will not load this file until every collision link above")
    lines.append("      # has at least one sphere here. See franka.xrdf for the expected shape.")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")
    print(f"  cspace joints     : {len(ARM_JOINTS)}")
    print(f"  collision links   : {len(COLLISION_LINKS)}")
    print(f"  self-collision ign: {sum(len(v) for v in ignore.values())} pairs across {len(ignore)} links")


if __name__ == "__main__":
    main()
