# Host-side RViz for visualizing the cuMotion plans that run in the container.
#
# RViz runs on the HOST (FastDDS, to match the container's RMW) and talks to the
# container's move_group over the shared network. The robot model is loaded from
# a HOST-generated URDF (package:// paths so the meshes resolve here, unlike the
# container's file:///workspaces URDF). Planning still happens in the container.
#
# Launched via view_cumotion.sh (sets RMW + generates the URDF).
import os
from pathlib import Path

import yaml
from launch import LaunchDescription
from launch_ros.actions import Node

URDF = "/tmp/oa_view.urdf"   # generated by view_cumotion.sh
CFG = os.path.join(
    os.path.dirname(__file__), "..")   # .../config


def load_yaml(path):
    with open(path) as f:
        return yaml.safe_load(f)


def generate_launch_description():
    urdf = Path(URDF).read_text()
    srdf = Path(os.path.join(CFG, "openarm_bimanual.srdf")).read_text()
    kinematics = load_yaml(os.path.join(CFG, "kinematics.yaml"))
    joint_limits = load_yaml(os.path.join(CFG, "joint_limits.yaml"))

    rviz_cfg = os.path.join(os.path.dirname(__file__), "cumotion.rviz")
    args = ["-d", rviz_cfg] if os.path.exists(rviz_cfg) else []

    rviz = Node(
        package="rviz2", executable="rviz2", output="screen",
        arguments=args,
        parameters=[
            {"robot_description": urdf},
            {"robot_description_semantic": srdf},
            {"robot_description_kinematics": kinematics},
            {"robot_description_planning": joint_limits},
            {"use_sim_time": False},
        ],
    )
    return LaunchDescription([rviz])
