x-gpu-config: &gpu-config
  runtime: nvidia
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    - RMW_IMPLEMENTATION=rmw_zenoh_cpp

x-cpu-config: &cpu-config
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    - RMW_IMPLEMENTATION=rmw_zenoh_cpp
  devices:
    - /dev/dri

services:
  robot_simulation:
    image: ghcr.io/eic-robocup-2026/walkie-ros/walkie-simulation:feat-github_action_ci-cd
    <<: [*cpu-config]
    container_name: robot-simulation
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # 1. FIX THE SRC MOUNT: Point it explicitly to your host's src folder
      - ../:/ros2_ws/src
      # 2. USE NAMED VOLUMES FOR CACHING
      - ros_build_cache:/ros2_ws/build
      - ros_install_cache:/ros2_ws/install
      - ros_log_cache:/ros2_ws/log
    # command: tail -f /dev/null
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               colcon build --symlink-install --parallel-workers 1 &&
               source install/setup.bash &&
               cd src/scripts &&
               ls &&
               bash sim_nav_gazebo.sh"

# 3. DECLARE THE NAMED VOLUMES AT THE BOTTOM OF THE FILE
volumes:
  ros_build_cache:
  ros_install_cache:
  ros_log_cache:
