services:
  zed_wrapper:
    image: zed-docker-zed_wrapper:latest
    user: root
    build:
      context: ../../..
      dockerfile: src/walkie-ros/docker/Dockerfile.physical
    container_name: robot_physical-zed_wrapper
    runtime: nvidia

    # Network and permissions
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    tty: true
    stdin_open: true
    group_add:
      - dialout

    # Environment
    environment:
      - USER
      - DISPLAY=${DISPLAY:?err}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=23
      # Uncomment if you actually use Zenoh:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp

    # GPU passthrough
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # Volumes
    volumes:
      # X11 for RViz / ZED tools
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Your local workspace (optional — only if you have custom packages)
      - ../../../src:/ros2_ws/src
      # Persistent ZED SDK AI models (avoids re-optimizing on every run)
      - zed_resources:/usr/local/zed/resources
      - zed_settings:/usr/local/zed/settings
      # USE NAMED VOLUMES FOR CACHING
      - ros_build_cache:/ros2_ws/build
      - ros_install_cache:/ros2_ws/install
      - ros_log_cache:/ros2_ws/log
      # Device passthrough for the camera (USB)
      - /dev:/dev

    # Just launch the ZED 2i wrapper
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash 
               cd /ros2_ws   
              #  apt update && 
              #  rosdep update 
              #  rosdep install --from-paths src -y -i  
               source /home/zed_deps_ws/install/setup.bash 
               colcon build --symlink-install --parallel-workers 1 
               source install/setup.bash 
               cd src/walkie-ros/bringup
               uv sync 
               cd /ros2_ws  
               ros2 run rmw_zenoh_cpp rmw_zenohd &
               ros2 launch robot_bringup lift_homing.launch.py &
               sleep 10
               ros2 launch robot_bringup real_omnibot.launch.py &
               sleep 5
               ros2 launch joy_interface joy_control_smooth.launch.py &
               ros2 launch robot_navigation localization_Nav2_real.launch.py &
               ros2 run walkie_perception ob_pose_service_cpp &
               ros2 launch openarm_bimanual_moveit_config  moveit_only.launch.py &
               ros2 launch openarm_bimanual_commander_cpp commander.launch.py"

volumes:
  zed_resources:
  zed_settings:
  ros_build_cache:
  ros_install_cache:
  ros_log_cache:  