<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dual_walkie_arm">
    
    <xacro:arg name="robot_name" default="dual_walkie_arm" />
    <xacro:arg name="base_link" default="base_link" />
    <xacro:arg name="use_gripper" default="true" />
    <xacro:arg name="arm_spacing" default="0.5" />
    <!-- <xacro:arg name="ros2_control_hardware_type" default="mock_components" /> -->
    <!-- <xacro:arg name="hardware_config_file" default="$(find arm_description)/config/hardware_layout.yaml" /> -->

    <xacro:include filename="$(find arm_description)/urdf/walkie-arm/walkie_arm.urdf.xacro" />
    <xacro:include filename="$(find arm_description)/urdf/walkie-gripper/walkie_gripper.urdf.xacro" />
    <!-- <xacro:include filename="$(find arm_description)/urdf/walkie/dual_arm_ros2_control.xacro" /> -->

    <link name="$(arg base_link)">
      <inertial>
        <origin xyz="0 0 0.025" rpy="0 0 0" />
        <mass value="2.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.015" />
      </inertial>
      <visual>
        <geometry>
          <box size="0.2 0.4 0.05" />
        </geometry>
        <origin xyz="0 0 0.025" rpy="0 0 0" />
        <material name="base_material">
          <color rgba="0.2 0.2 0.2 1.0" />
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="0.2 0.4 0.05" />
        </geometry>
        <origin xyz="0 0 0.025" rpy="0 0 0" />
      </collision>
    </link>

    <joint name="left_arm_mount_joint" type="fixed">
      <parent link="$(arg base_link)" />
      <child link="left_arm_base" />
      <origin xyz="0 ${$(arg arm_spacing)/2} 0.05" rpy="0 0 1.570796326794897" />
    </joint>

    <xacro:walkie_arm base_link="left_arm_base" prefix="left" />

    <xacro:if value="$(arg use_gripper)">
      <xacro:walkie_gripper parent="left_link6" prefix="left" />
    </xacro:if>


    <joint name="right_arm_mount_joint" type="fixed">
      <parent link="$(arg base_link)" />
      <child link="right_arm_base" />
      <origin xyz="0 ${-$(arg arm_spacing)/2} 0.05" rpy="0 0 -1.570796326794897" />
    </joint>

    <xacro:walkie_arm base_link="right_arm_base" prefix="right" />

    <xacro:if value="$(arg use_gripper)">
      <xacro:walkie_gripper parent="right_link6" prefix="right" />
    </xacro:if>

    <gazebo reference="$(arg base_link)">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <gazebo reference="left_arm_base">
      <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="right_arm_base">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- <xacro:dual_arm_ros2_control 
        name="DualWalkieSystem" 
        prefix=""
        hardware_config_file="$(arg hardware_config_file)"
    /> -->

</robot>