<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Main Macro -->
  <xacro:macro name="dual_arm_ros2_control" params="name prefix hardware_config_file">

    <!-- Load Hardware Configuration from YAML -->
    <xacro:property name="hw_config" value="${xacro.load_yaml(hardware_config_file)}"/>

    <!-- ========================================================== -->
    <!-- System 1: RealSystem (CubeMars)                            -->
    <!-- Included only if at least one joint is set to 'cubemars'   -->
    <!-- (We always generate it but it might be empty/unused if no joints are real) -->
    <!-- Actually, ros2_control might complain if empty. But let's assume valid config. -->
    <!-- ========================================================== -->
    
    <!-- Only generate RealSystem if 'cubemars' is present in the config -->
    <xacro:if value="${'cubemars' in hw_config['hardware_config'].values()}">
      <ros2_control name="RealSystem" type="system">
        <hardware>
          <plugin>cubemars_hardware/CubeMarsSystemHardware</plugin>
          <param name="can_interface">can0</param>
        </hardware>
        
        <!-- Configure Left Arm Joints -->
        <xacro:configure_joints_from_config prefix="left" target_type="cubemars" id_offset="10"/>
        <!-- Configure Right Arm Joints -->
        <xacro:configure_joints_from_config prefix="right" target_type="cubemars" id_offset="20"/>
      </ros2_control>
    </xacro:if>

    <!-- ========================================================== -->
    <!-- System 2: MockSystem (Generic)                             -->
    <!-- ========================================================== -->

    <ros2_control name="MockSystem" type="system">
      <hardware>
         <plugin>mock_components/GenericSystem</plugin>
      </hardware>
      
      <!-- Configure Left Arm Joints -->
      <xacro:configure_joints_from_config prefix="left" target_type="mock" id_offset="10"/>
      <!-- Configure Right Arm Joints -->
      <xacro:configure_joints_from_config prefix="right" target_type="mock" id_offset="20"/>
    </ros2_control>

  </xacro:macro>

  <!-- Macro to iterate and configure joints matching the target_type -->
  <xacro:macro name="configure_joints_from_config" params="prefix target_type id_offset">
    <!-- J1 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint1'] == target_type}">
      <xacro:configure_single_joint1 name="${prefix}_joint1" type="${target_type}" can_id="${id_offset + 1}"/>
    </xacro:if>
    <!-- J2 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint2'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint2" type="${target_type}" can_id="${id_offset + 2}"/>
    </xacro:if>
    <!-- J3 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint3'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint3" type="${target_type}" can_id="${id_offset + 3}"/>
    </xacro:if>
    <!-- J4 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint4'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint4" type="${target_type}" can_id="${id_offset + 4}"/>
    </xacro:if>
    <!-- J5 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint5'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint5" type="${target_type}" can_id="${id_offset + 5}"/>
    </xacro:if>
    <!-- J6 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint6'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint6" type="${target_type}" can_id="${id_offset + 6}"/>
    </xacro:if>
    <!-- J7 -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_joint7'] == target_type}">
      <xacro:configure_single_joint name="${prefix}_joint7" type="${target_type}" can_id="${id_offset + 7}"/>
    </xacro:if>
    <!-- Gripper -->
    <xacro:if value="${hw_config['hardware_config'][prefix + '_gripper_controller'] == target_type}">
      <xacro:configure_single_gripper name="${prefix}_gripper_controller" type="${target_type}" can_id="${id_offset + 8}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="configure_single_joint1" params="name type can_id">
    <joint name="${name}">
      <xacro:if value="${type == 'cubemars'}">
        <param name="can_id">${can_id}</param>
        <param name="pole_pairs">14</param>
        <param name="gear_ratio">100</param>
        <param name="kt">0.123</param>
        <param name="enc_off">0.0</param>
        <param name="trq_limit">30</param>
        <param name="read_only">0</param>
      </xacro:if>
      
      <command_interface name="position"/>
      <command_interface name="effort"/>
      <command_interface name="velocity">
        <xacro:if value="${type == 'cubemars'}">
           <param name="min">-16</param> <param name="max">16</param>
        </xacro:if>
      </command_interface>
      
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <xacro:if value="${type == 'cubemars'}">
        <state_interface name="temperature"/>
      </xacro:if>
    </joint>
  </xacro:macro>
  
  <!-- Macro for Single Joint Config -->
  <xacro:macro name="configure_single_joint" params="name type can_id">
    <joint name="${name}">
      <xacro:if value="${type == 'cubemars'}">
        <param name="can_id">${can_id}</param>
        <param name="pole_pairs">14</param>
        <param name="gear_ratio">10</param>
        <param name="kt">0.123</param>
        <param name="enc_off">0.0</param>
        <param name="trq_limit">30</param>
        <param name="read_only">0</param>
      </xacro:if>
      
      <command_interface name="position"/>
      <command_interface name="effort"/>
      <command_interface name="velocity">
        <xacro:if value="${type == 'cubemars'}">
           <param name="min">-16</param> <param name="max">16</param>
        </xacro:if>
      </command_interface>
      
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <xacro:if value="${type == 'cubemars'}">
        <state_interface name="temperature"/>
      </xacro:if>
    </joint>
  </xacro:macro>

  <!-- Macro for Single Gripper Config -->
  <xacro:macro name="configure_single_gripper" params="name type can_id">
    <joint name="${name}">
      <xacro:if value="${type == 'cubemars'}">
         <param name="can_id">${can_id}</param>
         <param name="pole_pairs">14</param>
         <param name="gear_ratio">1</param>
         <param name="kt">0.123</param>
         <param name="enc_off">0.0</param>
         <param name="trq_limit">5</param>
         <param name="read_only">0</param>
      </xacro:if>

      <command_interface name="position"/>
      <command_interface name="effort"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <xacro:if value="${type == 'cubemars'}">
        <state_interface name="temperature"/>
      </xacro:if>
    </joint>
  </xacro:macro>

</robot>